criação da entidade user
Maua-Dev/reservation_mss_user pull request #2
Opened 2024-10-18 19:52 UTC by gioalbuquerque

2024-10-28 21:10 UTC, Rubiozito requested changes

2024-10-28 21:10 UTC, Rubiozito commented on src/shared/domain/entities/user.py
> +    def validate_user_id(user_id: str) -> bool:
precisa melhorar um pouco esse validate userId, tem que garantir que ta no fromato de UUID, da uma refatorada nesse método pra validar isso

2024-10-28 21:10 UTC, Rubiozito commented on src/shared/domain/repositories/user_repository_interface.py
> +    def get_all_users(self) -> List[User]:
Falta a docSctring do método

2024-10-28 21:10 UTC, Rubiozito commented on src/shared/domain/repositories/user_repository_interface.py
Cade os demais métodos aqui? todos que tão no mock antes de adicionar la tem que estar aqui

2024-10-28 21:10 UTC, Rubiozito commented on tests/shared/domain/entities/test_user.py
> +    def test_invalid_user_id(self):
coloca um teste pra validar o formato do uuid, coloca uma string de uma letra

2024-10-29 01:05 UTC, lseixas commented on tests/shared/domain/entities/test_user.py
> +    def test_invalid_user_id(self):
adicionado

2024-10-30 17:46 UTC, Rubiozito approved these changes

2024-10-30 17:46 UTC, merged