load mock to dynamo
Maua-Dev/reservation_mss_user pull request #8
Opened 2024-11-13 22:51 UTC by lseixas

review?🥹

2024-12-17 00:47 UTC, Rubiozito requested changes

2024-12-17 00:47 UTC, Rubiozito commented on src/shared/infra/repositories/user_repository_dynamo.py
> +    def get_all_users(self) -> List[User]:
N temos nenhuma previsão pra usar um get_all_users, acho que por enquanto pode tirar

2024-12-17 00:47 UTC, Rubiozito commented on src/shared/infra/repositories/user_repository_dynamo.py
> +    def create_user(self, new_user: User) -> User:
Vamo tentar incluir o "attribute_not_exists", tem na documentação do dynamo e eu tenho uns exemplos pra se basear também

2024-12-17 00:47 UTC, Rubiozito commented on src/shared/infra/repositories/user_repository_dynamo.py
> +class UserRepositoryDynamo(IUserRepository, ABC):
Seria bom ja implementar um get_user_by_email, usando o LSI de email

2025-01-13 15:36 UTC, lseixas commented on src/shared/infra/repositories/user_repository_dynamo.py
> +    def create_user(self, new_user: User) -> User:
vamos usar o attribute_not_exists com que atributo? pelo que eu vi so podemos usar isso com chaves tipo PK, SK e Global. Pensei em usar com o email mas com LSI nao da pra usar pelo visto

2025-01-13 15:37 UTC, lseixas commented on src/shared/infra/repositories/user_repository_dynamo.py
> +    def get_all_users(self) -> List[User]:
feito

2025-01-13 15:37 UTC, lseixas commented on src/shared/infra/repositories/user_repository_dynamo.py
> +class UserRepositoryDynamo(IUserRepository, ABC):
feito

2025-01-16 01:13 UTC, Rubiozito approved these changes

2025-01-30 01:16 UTC, merged